services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - /Users/apple/docker-data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    command: redis-server --appendonly yes --requirepass redis!@#
    ports:
      - "6379:6379"
    volumes:
      - /Users/apple/docker-data/redis:/data
    restart: unless-stopped
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb-nosql
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - /Users/apple/docker-data/mongodb:/data/db
    restart: unless-stopped
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: elasticsearch-search
    environment:
      - discovery.type=single-node
      - ES_SECURITY_ENABLED=false
#      - ELASTIC_PASSWORD=elastic
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /Users/apple/docker-data/elasticsearch:/usr/share/elasticsearch/data
      - /Users/apple/docker-data/elasticsearch/config:/usr/share/elasticsearch/config
    restart: unless-stopped
    networks:
      - app-network
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # 注意：首次运行前需执行：sudo sysctl -w vm.max_map_count=262144

  rocketmq-nameserver:
    image: apache/rocketmq:5.1.4
    container_name: rocketmq-nameserver
    command: ["sh", "mqnamesrv"]
    ports:
      - "9876:9876"
    volumes:
      - /Users/apple/docker-data/rocketmq/logs:/root/logs
      - /Users/apple/docker-data/rocketmq/store:/root/store
    environment:
      JAVA_OPT_EXT: "-server -Xms256m -Xmx256m -Xmn128m"
    restart: unless-stopped
    networks:
      - app-network

  rocketmq-broker:
    image: apache/rocketmq:5.1.4
    container_name: rocketmq-broker
    command: ["sh", "mqbroker", "-n", "rocketmq-nameserver:9876", "-c", "/home/rocketmq/broker.conf"]
    ports:
      - "10911:10911"
      - "10909:10909"
    volumes:
      - /Users/apple/docker-data/rocketmq/logs:/root/logs
      - /Users/apple/docker-data/rocketmq/store:/root/store
      - /Users/apple/docker-data/rocketmq/broker.conf:/home/rocketmq/broker.conf
    environment:
      NAMESRV_ADDR: rocketmq-nameserver:9876
      JAVA_OPT_EXT: "-server -Xms256m -Xmx256m -Xmn128m"
    depends_on:
      - rocketmq-nameserver
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  mongodb_data:
  elasticsearch_data:
  rocketmq_data: