spring:
  application:
    name: tree-hole-server
  # PostgreSQL配置
  datasource:
    url: jdbc:postgresql://localhost:5432/treetalk
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        connection:
          # true 会导致回滚失败
          provider_disables_autocommit: false
    open-in-view: false
  
  # MongoDB配置
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://treetalk:treetalk@localhost:27017/treetalk}

    # Redis配置
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis!@#}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  # 缓存配置
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1小时
      cache-null-values: false
      use-key-prefix: true
      key-prefix: treetalk

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  


  # Flyway配置
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

# 服务器配置
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

# 日志配置
logging:
  level:
    com.treetalk: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/treetalk.log

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true
    enable-host: true
    enable-host-text: localhost:8080
  basic:
    enable: false

# 应用自定义配置
app:
  jwt:
    secret: ${JWT_SECRET:treeTalkSecretKey2024ForJWTTokenGenerationAndValidation}
    expiration: ${JWT_EXPIRATION:604800000} # 7天
  
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
  
  file:
    upload-dir: ${FILE_UPLOAD_DIR:./uploads}
    max-age: 3600
  
  ai:
    service:
      url: ${AI_SERVICE_URL:http://localhost:8081}
      timeout: 30000

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
